version: "3"

volumes:
  prometheus_data:
  grafana:

services:
  prometheus:
    image: prom/prometheus:v2.30.3
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ../prometheus/prometheus.yml:/tmp/prometheus.yml
      - ../prometheus/app.json:/tmp/app.json
    command:
      - "--config.file=/tmp/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 3001:9090
 
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SMTP_ENABLED=false
    ports:
      - 3000:3000

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.42.0
    command: --enable_metrics=cpu,cpuLoad,diskIO,memory,network
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    command: "-nginx.scrape-uri=http://nginx:8080/stub_status"

  redis-exporter:
    image: oliver006/redis_exporter:alpine
    environment:
      REDIS_ADDR: redis://redis:6379

  pgscv:
    image: weaponry/pgscv:latest
    environment:
      PGSCV_LISTEN_ADDRESS: 0.0.0.0:9890
      DATABASE_DSN: "postgresql://postgres:example@postgres/postgres"
      PGSCV_DISABLE_COLLECTORS: "system"
